.\"
.\" authoritydbus manual page
.\" Copyright (c) 2020 KylinSoftCo.Ltd <sunjunhao@kylinos.cn>
.\"
.TH AUTHORITYDBUS 1 "June 25 2020" ""
.SH NAME
authoritydbus \- Perform the settings that require the right to be raised.
.SH AUTHOR
\fBauthoritydbus\fR was written by Junhao Sun <sunjunhao@kylinos.cn>.
.PP
This manual page was originally written Junhao Sun <sunjunhao@kylinos.cn>.
.PP
This manual page was adopted for UKUI by Junhao Sun <sunjunhao@kylinos.cn>.
