.\"
.\" save-param manual page
.\" Copyright (c) 2020 KylinSoftCo.Ltd <sunjunhao@kylinos.cn>
.\"
.TH SAVE-PARAM 1 "June 25 2020" ""
.SH NAME
save-param \- Save the monitor parameter when updating usd
.SH AUTHOR
\fBsave-param\fR was written by Junhao Sun <sunjunhao@kylinos.cn>.
.PP
This manual page was originally written Junhao Sun <sunjunhao@kylinos.cn>.
.PP
This manual page was adopted for UKUI by Junhao Sun <sunjunhao@kylinos.cn>.
