.\"
.\" touchpad-state manual page
.\" Copyright (C) 2020 KylinSoft Co., Ltd.
.\"
.TH touchpad-state 1 "Nov 2020" "" "UKUI-SETTINGS-DAEMON"
.SH NAME
touchpad-state \- Modify touchpad status
.SH SYNOPSIS
touchpad-state
.SH DESCRIPTION
The \fItouchpad-state\fR  It is used to set the state of the touchpad, and it is more convenient to control the switch of the touchpad.
.PP
With \fItouchpad-state --off\fR Used to turn off the touchpad
.PP
With \fItouchpad-state --on\fR Used to open the touchpad
.SH AUTHOR
This manual page has been written by Shang Xiaoyang<shangxiaoyang@kylinos.cn>.

