.\"
.\" ukui₋settings-daemon manual page
.\" Copyright (c) 2009 Joshua Cummings <jrac@internode.on.net>
.\"
.TH UKUI-SETTINGS-DAEMON 1 "June 25 2009" ""
.SH NAME
ukui-settings-daemon \- Handles the UKUI session settings
.SH SYNOPSIS
\fBukui-settings-daemon\fR [\fB\-\-debug\fR] [\fB\-\-replace\fR]
[\fB\-\-display\fR=\fIDISPLAY\fR]
.SH DESCRIPTION
\fIukui-settings-daemon\fR is responsible for setting the various preference
parameters of a UKUI session and the applications that run under it.
.SH OPTIONS
.PP
Help options
.TP
\-?, \fB\-\-help\fR
Show this help message
.PP
Application options
.TP
\fB\-\^\-debug\fR
Enable debugging code
.TP
\fB\-\^\-replace\fR
Replaces the current running daemon
.TP
\fB\-\^\-display\fR=\fIDISPLAY\fR
X display to use
.PP
.SH AUTHOR
\fBukui-settings-daemon\fR was written by Jonathan Blandford <jrb@redhat.com>
and William Jon McCann <mccann@jhu.edu>.
.PP
This manual page was originally written by Joshua Cummings <jrac@internode.on.net>.
.PP
This manual page was adopted for UKUI by Vangelis Mouhtsis <vangelis@gnugr.org>.
