.\"
.\" ukydisplayswitch manual page
.\" Copyright (c) 2020 KylinSoftCo.Ltd <sunjunhao@kylinos.cn>
.\"
.TH ukydisplayswitch 1 "June 25 2020" ""
.SH NAME
ukydisplayswitch \- Toggle display mode of the monitor
.SH AUTHOR
\fBukydisplayswitch\fR was written by Junhao Sun <sunjunhao@kylinos.cn>.
.PP
This manual page was originally written Junhao Sun <sunjunhao@kylinos.cn>.
.PP
This manual page was adopted for UKUI by Junhao Sun <sunjunhao@kylinos.cn>.
