#!/bin/bash
set -e

function cleanconfig() {
    desktop="/etc/xdg/autostart/kylin-display-switch-daemon.desktop"
    if [ -f "${desktop}" ];then
        rm ${desktop}
        echo "${desktop} has been deleted!"
    fi
    desktop2="/etc/xdg/autostart/kylin-display-switch-mkt.desktop"
    if [ -f "${desktop}" ];then
        rm ${desktop}
        echo "${desktop} has been deleted!"
    fi
}
function stoptouchegg() {
    if [ -d /run/systemd/system ]; then
        systemctl stop 'kylin-display-switch.service' >/dev/null || true
        systemctl disable 'kylin-display-switch.service' >/dev/null || true
        systemctl --system daemon-reload >/dev/null || true
        echo "Stop kylin-display-switch Success !"
    fi
}

echo "file = $#, param = $@"

if [ "$#" == 1 ] && [ "$1" == "reconfigure" ]; then
    # OTA升级时的执行分支
    echo "Total parameter is 1"
    stoptouchegg
    cleanconfig
else
    # 安装包正常安装的安装后脚本执行顺序
    stoptouchegg
    cleanconfig
    systemctl enable testupdate
fi

echo "testUpdate's postinst has been executed!"
