#!/bin/sh
set -e

PowerIgnorePath="/etc/systemd/logind.conf.d/"
PowerIgnorePathFile="power-ignore.conf"

if [ ! -d "$PowerIgnorePath" ];then
  mkdir $PowerIgnorePath
fi

if [ ! -f "$PowerIgnorePath$PowerIgnorePathFile" ];then
  touch $PowerIgnorePath$PowerIgnorePathFile
  echo "[Login]" >> $PowerIgnorePath$PowerIgnorePathFile
  echo "HandlePowerKey=ignore" >> $PowerIgnorePath$PowerIgnorePathFile
fi

glib-compile-schemas /usr/share/glib-2.0/schemas/
