/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp usd-xrandr-manager.xml -a xrandr-adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef XRANDR-ADAPTOR_H
#define XRANDR-ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.ukui.SettingsDaemon.xrandr
 */
class XrandrAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ukui.SettingsDaemon.xrandr")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.ukui.SettingsDaemon.xrandr\">\n"
"    <signal name=\"screenPrimaryChanged\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"x\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"y\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"width\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"height\"/>\n"
"    </signal>\n"
"    <method name=\"x\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"y\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"width\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"height\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"priScreenChanged\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"width\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"height\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    XrandrAdaptor(QObject *parent);
    virtual ~XrandrAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int height();
    int priScreenChanged(int x, int y, int width, int height);
    int width();
    int x();
    int y();
Q_SIGNALS: // SIGNALS
    void screenPrimaryChanged(int x, int y, int width, int height);
};

#endif
