.\" UKUI manpages
.\" usd-datetime-mechanism -man
.\"
.TH usd-usb-monitor 1 "Sep 2020" "" "UKUI-SETTINGS-DAEMON"
.SH NAME
usd-usb-monitor \- Monitor USB keyboard plug-in events
.SH SYNOPSIS
usd-usb-monitor
.SH DESCRIPTION
The \fIusd-usb-monitor\fR 
This helps monitor the plugging and unplugging of usb keyboard devices
.PP
With \fIukui-settings-daemon\fR i is possible to assign a hotkey for evoking
the \fIusd-usb-monitor\fR command.
.SH AUTHOR
This manual page has been written by Shang Xiaoyang <shangxiaoyang@kylinos.cn>.
