.\" UKUI manpages
.\" usd-datetime-mechanism -man
.\"
.TH usd-locate-pointer 1 "Oct 2014" "" "UKUI-SETTINGS-DAEMON"
.SH NAME
usd-locate-pointer \- create ripples around mouse pointer
.SH SYNOPSIS
usd-locate-pointer
.SH DESCRIPTION
The \fIusd-locate-pointer\fR utility is a program that creates ripples (like throwing a stone into water)
around the mouse pointer. This helps to locate the position of the mousepointer.
.PP
With \fIukui-settings-daemon\fR i is possible to assign a hotkey for evoking
the \fIusd-locate-pointer\fR command.
.SH AUTHOR
This manual page has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de>.
It has been originally written for the Debian project (but may be used by others)